### ISSUE TITLE
Input Values in Arduino Sketch

### ISSUE THREAD

**Issue by jay765** [microsoft/EdgeML#109]
Hello!
I am using the SeeDot to generate the code for the Arduino and I have some questions regarding the Arduino Sketch.
1.) Where do the test values in array X stored in devices' flash memory come from?
2.) How do the input values need to be presented? I am using Bonsai to create the model, the training and test data in presented as integer values. When using the Arduino sketch, do the input values need to be scaled? If so, which scaling factor should be used? The data stored in array X has different values than any training-/testdata used to create the model.

Thank you very much!

**Comment by metastableB** [comment]
@sridhargopinath Please have a look.
