### ISSUE TITLE
Testing pytorch implementations.

### ISSUE THREAD

**Issue by metastableB** [microsoft/EdgeML#117]
Leaving this issue here to keep track of developments.

- Need to test every algorithm again with the runner suits.
- Re-run notebooks and push new updates whenever that makes sense.
- Test SRNN updates, with and without dropout.

**Comment by pushkalkatara** [comment]
Hi, can I contribute to a subpart of the issue?

**Comment by harsha-simhadri** [comment]
@pushkalkatara  Sure, would appreciate if you could test PR 118.

**Comment by pushkalkatara** [comment]
Hi, I tested the PR #118 and made some small changes proposed here - https://github.com/microsoft/EdgeML/pull/120
