### ISSUE TITLE
FastGRNN Arduino/C++ code

### ISSUE THREAD

**Issue by LucaCerina** [microsoft/EdgeML#126]
Hello, I have a brief question about the results in the NIPS paper.

Did you use seeDot to generate the fastRNN/fastGRNN on Arduino, or is it something that you built from scratch and it is not yet available on the repo?

Thank you.

**Comment by adityakusupati** [comment]
@LucaCerina the Arduino/C++ code is not available in the repo. However, the final quantized models can be obtained from the training scripts. The c++ code is typically a for loop with a couple of MatVec ops for RNNs. You could email @SachinG007 for the C++ codes used given they are not public yet.

**Comment by LucaCerina** [comment]
Thank you so much, I will contact him
