### ISSUE TITLE
How do we train new gestures for GesturePod?

### ISSUE THREAD

**Issue by maxsu** [microsoft/EdgeML#134]
Please forgive me if this question is answered elsewhere. How would we generate new models for custom gestures?

**Comment by ShishirPatil** [comment]
Hi Maxsu,

Please refer to the [modelTraining branch](https://github.com/microsoft/EdgeML/tree/modelTraining). 
Note that this is still WIP.

Thanks,

**Comment by maxsu** [comment]
Thanks for the response Shishir! I look forward to working with this system on the [M5StickC](https://m5stack.com/products/stick-c).

I am pleased to see a microcontroller scale AI includes not only a final model, but also the the means to train that model. Kudos to you and your team!
