### ISSUE TITLE
ModuleNotFoundError: No module named 'edgeml.trainer'

### ISSUE THREAD

**Issue by ccu1tn** [microsoft/EdgeML#145]
Dear every one; 

When I run this command python bonsai_example.py -dir usps10/. This source appears a this error 
![image](https://user-images.githubusercontent.com/43333942/69107422-49fa1400-0aac-11ea-846e-6e483b53fbe2.png)
I'm looking way how to fix it like uses pip install module named 'edgeml.trainer'.  But It is not done. 
so. What is the module I need to install for this errors?

Many thanks!

**Comment by adityakusupati** [comment]
Hi,

I think you are trying to run the tensorflow version bonsai_example.py after installing pytorch version of the edgeml module. It would be great if you can attach the sequence of instructions you have followed for the same. 

Aditya

**Comment by ccu1tn** [comment]
Dear @adityakusupati 
Thank you so much.. It worked.
