### ISSUE TITLE
Installing the library

### ISSUE THREAD

**Issue by Giuseppe5** [microsoft/EdgeML#154]
Hi,

I was trying to install the library to try the KWS example in pytorch. However when executing "pip install .", the installation fails with the following error:
`error: could not create build/bdist.linux-x86_64/wheel/edgeml_pytorch  : No such file or directory
Error: Failed building wheel for fastgrnn-cuda`

If I try with "pip install -e .", I get no error but when trying to import fastgrnn_cuda I get the following:
` ImportError: /edgeml/pytorch/fastgrnn_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE `

I'm using pytorch 1.1.0.

Could you please help me?

**Comment by adityakusupati** [comment]
I tried installing everything using pytorch 1.2.0 and it works fine. I am not sure what is going wrong. Can you check your CUDA version?
