### ISSUE TITLE
Could you provide a Demo about wake word using FastGRNN?

### ISSUE THREAD

**Issue by shipleyxie** [microsoft/EdgeML#156]
Now I want to use your source code in Keras in which there is a already setted wake up word recogniton system, it turns out I can't use your source code directly in Keras.
Should i rewrite your FastGRNN code in Keras?

**Comment by ShishirPatil** [comment]
@adityakusupati Do you have any inputs?

**Comment by adityakusupati** [comment]
Keras should support TF backend, we are not providing any TF 2.x support so, if there is a compatibility issue, you should re-write FastGRNNCell and TF 2.x has support for custom RNN Cells.
