### ISSUE TITLE
EdgeML on Raspberry Pi 3

### ISSUE THREAD

**Issue by jong1prk** [Microsoft/EdgeML#16]
I have tried to run Bonsai and ProtoNN on Raspberry Pi 3. 

But, there was a problem with MKL installation.

MKL only runs on the Intel processor not ARM processor.

You guys mentioned that you've tested on Arduino Uno, 

but I wonder how that is possible.

**Comment by harsha-simhadri** [comment]
@jong1prk,

This code was written for training the model. We do it on our laptop/workstation, which has Intel processors (hence MKL library). The idea is that you take the model and make predictions on Raspberry.

If you'd like to use this training code on Raspberry Pi, we suggest you try another implementation of BLAS routines that works on Raspberry Pi. I imagaine it will required minor code changes (disable all sparse matrices) as well as make file changes. If you would like to do this and you have an appropriate BLAS library for Raspberry which has math calls, we can help you. 

And we will be glad to merge your changes so others can use it.
