### ISSUE TITLE
Dead link to the Paper

### ISSUE THREAD

**Issue by binga** [microsoft/EdgeML#161]
Hi team,

The link to the paper on the following link is broken, in the README.md of the repository - https://github.com/microsoft/EdgeML/blob/master/docs/publications/ICane-UIST19.pdf

Could you help us with this? Thanks!

**Comment by ShishirPatil** [comment]
Here is a link for the paper: https://github.com/microsoft/EdgeML/blob/master/docs/publications/GesturePod-UIST19.pdf. Will update the readme. Thanks!
