### ISSUE TITLE
Refactoring out serialization code

### ISSUE THREAD

**Issue by sureshiyengar** [Microsoft/EdgeML#17]
Move the serialization code out of Bonsai model. One option is to have a serialization base class and different strategies for custom export which takes in a Bonsai model.

**Comment by adityakusupati** [comment]
Hi @sureshiyenger,

Can you be more specific regarding the features you are talking about? Can you point me to the file and line number of the same?

Aditya

**Comment by sureshiyengar** [comment]
Check void BonsaiModel::exportModel

Ideally, all the serialization logic can go into a separate class. The model class does not change if a new serialization format needs to be added.

**Comment by adityakusupati** [comment]
Seems like a good idea. Will look into it.

**Comment by sureshiyengar** [comment]
One thought I had was having a SerializationBase which defines the interface. The function takes in the BonsaiModel as output and serializes it into different format, more like a strategy pattern.
