### ISSUE TITLE
Byte Quantization (Q) for model compression

### ISSUE THREAD

**Issue by mehreenjabeen** [microsoft/EdgeML#176]
Hi,
Please clarify whether quantizeBonsaiModels.py in https://github.com/microsoft/EdgeML/tree/master/examples/tf/Bonsai is doing the same quantization as done by https://github.com/microsoft/EdgeML/tree/master/tools/SeeDot?

Thanks

**Comment by adityakusupati** [comment]
Something similar, but not exactly. SeeDot uses the dataset to figure out the scale while quantizeBonsaiModels.py gives complete freedom to the user. Using either of them is fine, but SeeDot is preferred in case you don't want to look under the hood.

**Comment by mehreenjabeen** [comment]
Thanks for explaining.

**Comment by AmbiTyga** [comment]
I want to run pytorch Bonsai model on different memory size, how can i do that?
