### ISSUE TITLE
SeeDot Compiler issue

### ISSUE THREAD

**Issue by AbdelilahTAHIRI** [microsoft/EdgeML#185]
Hello,

While trying to generate the arduino sketch for ProtoNN trained on ups10 dataset as explained in the given example here:  https://github.com/microsoft/EdgeML/blob/f04237c664eea1e821733928101c34d3730573c3/tools/SeeDot/README.md

The results of` python SeeDot.py command` are:
- These files are generated as expected:  `arduino.ino`, `library.h`, `config.h,` `predict.h `and `model.h`
- The predict.cpp file contains errors: The library functions arguments are mispositioned. For example the sparse matrix multiplication function is declared in the library.h as `SparseMatMul(const MYINT *Aidx, const MYINT *Aval, MYINT *C, MYINT K, MYINT shrA, MYINT shrB, MYINT shrC )`. It is called in the `predict.cpp` as follows: `SparseMatMul(&Widx[0], 128, &Wval[0], 256, 256, &tmp5[0][0], 128);`
- While running the command, there same issues are encountered with the code present at /tmp/ folder. Here is a screen-shot of the SeeDot.py output

![Scrren_SeeDot_ProtoNN](https://user-images.githubusercontent.com/45886948/84669515-3b31ed80-af25-11ea-9f6b-af6d493e8760.png)

Please need help with this.

**Comment by adityakusupati** [comment]
@aayan636

**Comment by AbdelilahTAHIRI** [comment]
Finally the issue disappear just by switching from Python3.5 to Python3.6.
