### ISSUE TITLE
Remove hardcodings

### ISSUE THREAD

**Issue by sureshiyengar** [Microsoft/EdgeML#20]
Remove hardcodings of file paths

std::ifstream ifs("/home/t-vekusu/ICMLDatasets/multiclass/mnist/train");

#pragma comment(lib, "../../../../Libraries/MKL/Win/Microsoft.MachineLearning.MklImports.lib")

**Comment by adityakusupati** [comment]
Removed std::ifstream ifs("/home/t-vekusu/ICMLDatasets/multiclass/mnist/train");

**Comment by euler16** [comment]
Hi, is this issue still open? if yes then can I take this up?
