### ISSUE TITLE
[ASK] : Bonsai model on Azure IoT Edge

### ISSUE THREAD

**Issue by vermaaditya** [microsoft/EdgeML#210]
Hi Team, 

We are trying to deploy the Bonsai Models on a Machine in the plant hosting Azure IOT Edge runtime. 
Is there a reference documentation which can be leveraged? Or do you have a suggested deployment pattern to achieve the same on Azure IoT Edge in the form of Modules? Or if the Bonsai interface https://preview.bons.ai/workspaces directly provides an interface to deploy the model to Azure IoT Edge?

Kindly suggest.

Thanks,

**Comment by SachinG007** [comment]
Hi Aditya,
Can you please check if you are referring to the correct Bonsai, this repository is for the ICML'17 publication Bonsai (https://github.com/microsoft/EdgeML/blob/master/docs/publications/Bonsai.pdf) , which is a strong non linear tree based classifier.

**Comment by SachinG007** [comment]
Hi @vermaaditya ,
Can you please check if you are referring to the correct Bonsai, this repository is for the ICML'17 publication Bonsai (https://github.com/microsoft/EdgeML/blob/master/docs/publications/Bonsai.pdf) , which is a strong non linear tree based classifier.

**Comment by vermaaditya** [comment]
Looks like an incorrectly posted question, thanks for clearing the confusion. The question was meant to be for - https://github.com/BonsaiAI/bonsaiai.github.io

Closing the issue.
