### ISSUE TITLE
Unable to download dataset 

### ISSUE THREAD

**Issue by pankaja0285** [microsoft/EdgeML#226]
- I cloned the repo 
- In anaconda prompt installed all the required libraries in requirements.txt
- opened in pycharm on my desktop 
- tried to run download_mscoco.sh with edit configurations - set to folder for e.g. "coco-dataset" and click run, it just opens up the cmd prompt very quickly and closes up. The download doesn't happen. 

What am I doing wrong? Please advice.
<img width="774" alt="dataset_dwl_err" src="https://user-images.githubusercontent.com/54913075/103606871-87567680-4ee5-11eb-9af6-2bfe0ad9bf20.PNG">

**Comment by SachinG007** [comment]
@oindrilasaha

**Comment by oindrilasaha** [comment]
Hi, can you please ensure that you have set the script as executable?
