### ISSUE TITLE
Inference Code to deploy KWS on bluecoin

### ISSUE THREAD

**Issue by mehreenjabeen** [microsoft/EdgeML#233]
Hi, 

I have generated the four files(model.h, model.S, featurizer.h and featurizer.S) for cortex M4 devices. However, I didnt find any inference code for deployment on STM bluecoin.  Can you please provide any pointer on it.

Thanks

**Comment by ShikharJ** [comment]
@MJ10 Can you please take a look at this as well?

**Comment by ShikharJ** [comment]
@mehreenjabeen The STM Bluecoin driver code is Microsoft IP, and as such cannot be shared. Sorry for this. Closing the issue for now.
