### ISSUE TITLE
The model of DROCC seems missing

### ISSUE THREAD

**Issue by NoThinG-qh** [microsoft/EdgeML#252]
Thank you for the contribution to one class classification. DROCC is an excellent algorithm, but it seems that only the trainer of DROCC was found in this code repository , I could not find the model of DROCC. Can the model be published?

**Comment by ShikharJ** [comment]
@NoThinG-qh Thanks for your interest in DROCC. I think trained models have license conflicts with the repository, so we don't publish them. One can always use the trainer code for generating the models again.

**Comment by SachinG007** [comment]
@NoThinG-qh you can use the CLI commands here to generate trained models https://github.com/microsoft/EdgeML/tree/master/examples/pytorch/DROCC

**Comment by ShikharJ** [comment]
Closing for now.
