### ISSUE TITLE
Run ProtoNN

### ISSUE THREAD

**Issue by tushargupta5197** [Microsoft/EdgeML#26]
I am trying to execute the ProtoNN algorithm on my ubuntu 16.04 machine. However, I am unable to interpret what inputs to provide to the code and in what format. Kindly provide a small instruction set on how to run ProtoNN for the training and testing data you specified in the readme.
Thanks

**Comment by suvadeep-iitb** [comment]
Please refer to README.md to get instructions for building and executing
demo. And for detailed description of ProtoNN command line argument, please
refer to README_PROTONN_OSS.md under the doc/ folder.

Regards,
Suvadeep Hajra
PhD Student,
IIT Bombay, India
