### ISSUE TITLE
For Image Anomaly, custom dataset

### ISSUE THREAD

**Issue by aytek03** [microsoft/EdgeML#263]
Hi  sir,

Your main_cifar.py code runs on cifar-dataset but I want to try custom dataset.

I create .pickle file (x_train etc.) but When I switch download=False, create  and build my own pickle train files then

       ( train_set = MyCIFAR10(root=self.root, train=False, download=False
                              transform=transform, target_transform=target_transform)   in process_cifar.py (line 67)

I got an error: = RuntimeError: Dataset not found or corrupted. You can use download=True to download it.

How can I added my pickle file to the code?

**Comment by aytek03** [comment]
Hi  sir,

Your main_cifar.py code runs on cifar-dataset but I want to try custom dataset.

I create .pickle file (x_train etc.) but When I switch download=False, create  and build my own pickle train files then

       ( train_set = MyCIFAR10(root=self.root, train=False, download=False
                              transform=transform, target_transform=target_transform)   in process_cifar.py (line 67)

I got an error: = RuntimeError: Dataset not found or corrupted. You can use download=True to download it.

How can I added my pickle file to the code?

**Comment by SachinG007** [comment]
Hi @aytek03 ,
If you have your own dataset (say x_train and y_train), maybe you will not even need to run process_cifar.py ? That code is just to overwrite the pytorch CIFAR loader to load normal and abnormal class accordingly. 
I would suggest you can modify your pickle file's y_train to label them 0 (abnormal) and 1 (normal). 

I would be more than happy to help you further, if you can provide more details.

Thanks
Sachin

**Comment by aytek03** [comment]
How can I do not run process_cifar.py?

In main_cifar.py, we have this line:

dataset = CIFAR10_Dataset("data", args.normal_class).

**Comment by SachinG007** [comment]
What I meant was you can accordingly modify the dataloading part of the code based on your requirements. 
For ex., if you are using your own custom data with images in a local folder, you can replace line 67 in process_cifar.py with https://pytorch.org/vision/main/generated/torchvision.datasets.ImageFolder.html

If you have a pickle file which loads the whole data, then I would suggest you to look at main_tabular.py, which also deals with loading data from a pickle file (tabular datasets) which you can modify accordingly as per your needs.

**Comment by SachinG007** [comment]
Hi @aytek03 ,
Can I consider this issue resolved ?

Thanks
Sachin

**Comment by aytek03** [comment]
Yes this issue is resolved. @SachinG007 

If a some problem arises again, can I bother you?

Thanks.

**Comment by SachinG007** [comment]
Hi @aytek03 
We will be more than happy to help you out 
Thanks for taking interest in our work

-Sachin
