### ISSUE TITLE
tensorflow data files

### ISSUE THREAD

**Issue by jacobrosenthal** [Microsoft/EdgeML#44]
A bunch of directions call for loading from a test or train.npy file. The text seems to be a list of label featurenum:float ...  and doing np.load on the .txt doesnt work as I get `UnpicklingError ` Any help?

Also what/where is CURET data?

**Comment by metastableB** [comment]
@jacobrosenthal  Apologies for the confusion. We were initially using `.npy` files as our default input format. Currently we have decided to move to `.text` - this confusion could be a result of this?

Can you let me know where exactly you are facing this error:
Specifically can you let me know the branch/commit information and the command you are using to run.

@adityakusupati  Can you help with CURET ? Else lets move to MNIST?

**Comment by metastableB** [comment]
@adityakusupati  `master` might still have remnants of the old _README.md_ with instructions for `npy` file. Can you update this? I'll rebase with your changes once you are done.

**Comment by adityakusupati** [comment]
@jacobrosenthal , I think I understand your issue. First of all tf codes use .npy files as input and not .txt, this is done for consistency reasons. So the txt files being used for C++ codebase has to be formatted to .npy file. If it is a tsv or csv then you can convert .txt to .npy using np.loadtxt followed by np.save. 

Now, the txt files for usps10 used for C++ code are in libsvm format and need a special pre-processor to get to .npy format. You can find the new instructions (still in PR, will be in master in a couple of days) here - https://github.com/Microsoft/EdgeML/tree/TF-EdgeML/tf . Please follow the instructions and let me know if you have any other issues. Also, tf Readme even in master explicitly mentions the format for .npy files to be fed in. Lastly, CURET is one of the datasets used in our ICML papers, you can find the dataset here - http://www.robots.ox.ac.uk/~vgg/research/texclass/# , but it has feature extraction, which hasn't been released, so you can test out your code on usps10 using the instructions mentioned in TF-EdgeML branch. Let me know if you find any other issues.

**Comment by adityakusupati** [comment]
@jacobrosenthal , if things are working we would like close this issue. Let us know.,
