### ISSUE TITLE
Feature extractor script for HAR is buggy.

### ISSUE THREAD

**Issue by metastableB** [Microsoft/EdgeML#49]
The the data produced at the end does not match the data used in publication in terms of the number of data points at least.

**Comment by chogba** [comment]
[#47](https://github.com/Microsoft/EdgeML/pull/47) resolves this. The number of test data points is consistent. To get consistent number of points in val and train sets, set seed to 42 before shuffling subjects in `generateIndicesForSplits` in helpermethods.py

**Comment by chogba** [comment]
[#47](https://github.com/Microsoft/EdgeML/pull/47) resolves this. The number of test data points is consistent. To get consistent number of points in val and train sets, set seed to 42 before shuffling subjects in `generateIndicesForSplits()` in helpermethods.py
