### ISSUE TITLE
Issue in Running EMI-RNN notebooks with fetched HAR dataset

### ISSUE THREAD

**Issue by adityakusupati** [Microsoft/EdgeML#50]
@metastableB and @chogba, the Notebook doesn't run out of the box, there is dimensionality mismatch in the dataset and the core utility. Please fix it.

**Comment by metastableB** [comment]
Can you test now? This should be fixed with #43 commit commit 7770e05. Can you test and close ?

**Comment by metastableB** [comment]
Fixed in #43.
