### ISSUE TITLE
Error in run_ProtoNNPredict_usps10.sh

### ISSUE THREAD

**Issue by Jaystings** [Microsoft/EdgeML#55]
There is a simple issue in the script that runs ProtoNNPredict on the example data set. I have highlighted the issue in the image I provided: the number of iterations is supposed to be 20 and not 2. Please fix this in one of the next commits so that it will run immediately after cloning the project and building it. 
![edgemlbug](https://user-images.githubusercontent.com/4793654/45504383-b74b4000-b757-11e8-917c-a6b2e325f184.PNG)

**Comment by harsha-simhadri** [comment]
@Jaystings Thanks for pointing this out. Fixed it
