### ISSUE TITLE
Will you release the code to reproduce the keyword spotting results in your FastGRNN paper?

### ISSUE THREAD

**Issue by ifed-ucsd** [Microsoft/EdgeML#72]

**Comment by adityakusupati** [comment]
Hi @ifed-ucsd ,

The training code along with the quantization is public and is already in the repo at: https://github.com/Microsoft/EdgeML/tree/master/tf/examples/FastCells. I am not sure what is that you want to be public. If you are talking about the Wakeword-2 dataset, unfortunately, it is proprietary. But one can use Google Keyword dataset as a substitute.  The FastGRNN paper describes the featurization as well for the keyword spotting datasets. Lastly, if you want IoT device code, we haven't released the handwritten Arduino code as we are expecting the release of SeeDot a compiler to generate optimized code for the devices. You can write a native C implementation and it should work. An example for one of the hand written codes is: https://github.com/Microsoft/EdgeML/blob/master/Applications/GesturePod/onMKR1000/onMKR1000.ino
We have also shared the hyperparams for the datasets in the Appendix of the paper. 

Do let me know if there is something else you need.

Thanks
