### ISSUE TITLE
Error in  EdgeML/tf/examples/FastCells/helpermethods.py 

### ISSUE THREAD

**Issue by ShilpaSangappa** [Microsoft/EdgeML#79]
Method saveMeanStd(mean, std, currDir):
Line number 267, 268 is:
np.save(os.path.join(dataDir, 'mean.npy'), mean)
np.save(os.path.join(dataDir, 'std.npy'), std)

Error: variable dataDir is undefined.

I guess it has to be:
np.save(os.path.join(currDir, 'mean.npy'), mean)
np.save(os.path.join(currDir, 'std.npy'), std)

Shall I raise a PR?

**Comment by adityakusupati** [comment]
Hi,

Thanks a lot for the heads up. I have fixed it now. Can you please confirm the same :)

**Comment by ShilpaSangappa** [comment]
I have tested with the currDir variable yesterday. It worked.
